"""The OpenResponses ``Item`` union.

An Item is the atomic unit of context: a request carries input items and a
response carries output items. The union mirrors the specification's
``ItemField`` exactly — ``message``, ``reasoning``, ``function_call``,
``function_call_output`` and ``compaction`` — plus :class:`ExtensionItem`, the
escape hatch that preserves any slug-prefixed implementer item verbatim.

``id`` and ``status`` are optional because BoThesis authors input items itself
(a user message has neither until a server assigns them); every item observed
on a response stream carries both.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Annotated, Any, Literal, TypeAlias, Union

from pydantic import Discriminator, Field, Tag, TypeAdapter, field_validator

from bothesis.agent.protocol import (
    EXTENSION_TAG,
    ExtensibleProtocolModel,
    ProtocolModel,
)
from bothesis.agent.protocol.content import (
    TEXT_PART_TYPES,
    ContentPart,
    ReasoningContent,
    ReasoningText,
    SummaryText,
)

ItemStatus: TypeAlias = Literal["in_progress", "completed", "incomplete"]
"""The specified item state machine.

``in_progress`` while the model samples the item, ``completed`` when sampling
finished, ``incomplete`` when the model was interrupted partway through — which
must be the last item of an ``incomplete`` response. Runtime outcomes such as a
tool timeout are telemetry, not item status.
"""

MessageRole: TypeAlias = Literal["system", "developer", "user", "assistant"]

MessagePhase: TypeAlias = Literal["commentary", "final_answer"]
"""Whether an assistant message is intermediate commentary or the answer.

The specification requires ``phase`` to be preserved and resent on every
follow-up request; dropping it degrades model performance.
"""

CORE_ITEM_TYPES = frozenset(
    {
        "message",
        "reasoning",
        "function_call",
        "function_call_output",
        "compaction",
    }
)


class MessageItem(ProtocolModel):
    """One conversation message addressed to or produced by the model."""

    type: Literal["message"] = "message"
    role: MessageRole
    content: tuple[ContentPart, ...]
    id: str | None = None
    status: ItemStatus | None = None
    phase: MessagePhase | None = None

    @property
    def text(self) -> str:
        """Concatenate the textual parts, ignoring images, files, and refusals."""

        return "".join(
            part.text for part in self.content if isinstance(part, TEXT_PART_TYPES)
        )


class ReasoningItem(ProtocolModel):
    """Reasoning generated by the model.

    ``content`` holds raw reasoning text, ``summary`` the provider-authored
    public summary, and ``encrypted_content`` the opaque blob a provider needs
    to continue a reasoning session. Those three fields are what a reasoning
    item needs to replay losslessly, so no BoThesis-specific field is added
    here.
    """

    type: Literal["reasoning"] = "reasoning"
    id: str | None = None
    content: tuple[ReasoningContent, ...] = ()
    summary: tuple[ReasoningContent, ...] = ()
    encrypted_content: str | None = None
    status: ItemStatus | None = None

    @property
    def reasoning_text(self) -> str:
        return "".join(part.text for part in self.content)

    @property
    def summary_text(self) -> str:
        return "".join(part.text for part in self.summary)


class FunctionCallItem(ProtocolModel):
    """A model request to call one function tool.

    ``arguments`` stays the JSON string the provider emitted so nothing is lost
    when the item is echoed back on the next request. Use
    :meth:`parsed_arguments` to decode it.
    """

    type: Literal["function_call"] = "function_call"
    call_id: str = Field(min_length=1)
    name: str = Field(min_length=1)
    arguments: str = ""
    id: str | None = None
    status: ItemStatus | None = None

    def parsed_arguments(self) -> dict[str, Any]:
        """Decode ``arguments`` into a JSON object.

        Raises ``ValueError`` when the model produced invalid JSON or a
        non-object, so callers can turn it into a tool observation instead of
        guessing what the model meant.
        """

        if not self.arguments.strip():
            return {}
        try:
            value = json.loads(self.arguments)
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"function call arguments are not valid JSON: {self.name}"
            ) from exc
        if not isinstance(value, Mapping):
            raise ValueError(
                f"function call arguments are not a JSON object: {self.name}"
            )
        return dict(value)


class FunctionCallOutputItem(ProtocolModel):
    """The observation returned for one ``function_call``.

    Developer-supplied outputs are always ``completed``: a tool failure is
    reported inside ``output``, never as an item status the specification does
    not define.
    """

    type: Literal["function_call_output"] = "function_call_output"
    call_id: str = Field(min_length=1)
    output: str
    id: str | None = None
    status: ItemStatus | None = "completed"


class CompactionItem(ProtocolModel):
    """Conversation state a provider compacted into an opaque blob."""

    type: Literal["compaction"] = "compaction"
    encrypted_content: str
    id: str | None = None
    created_by: str | None = None


class ExtensionItem(ExtensibleProtocolModel):
    """A slug-prefixed implementer item preserved verbatim.

    This is the item-level escape hatch. It accepts any ``type`` outside
    :data:`CORE_ITEM_TYPES` and keeps every additional field, so items the
    protocol does not model can still be replayed to their originating
    provider on later requests.
    """

    type: str = Field(min_length=1)
    id: str | None = None

    @field_validator("type")
    @classmethod
    def _reject_core_types(cls, value: str) -> str:
        if value in CORE_ITEM_TYPES:
            raise ValueError(f"{value} is a core protocol item type")
        return value


def _item_tag(value: Any) -> str:
    """Route core item types to their model and anything else to the hatch."""

    raw_type = (
        value.get("type")
        if isinstance(value, Mapping)
        else getattr(value, "type", None)
    )
    if isinstance(raw_type, str) and raw_type in CORE_ITEM_TYPES:
        return raw_type
    return EXTENSION_TAG


Item: TypeAlias = Annotated[
    Union[
        Annotated[MessageItem, Tag("message")],
        Annotated[ReasoningItem, Tag("reasoning")],
        Annotated[FunctionCallItem, Tag("function_call")],
        Annotated[FunctionCallOutputItem, Tag("function_call_output")],
        Annotated[CompactionItem, Tag("compaction")],
        Annotated[ExtensionItem, Tag(EXTENSION_TAG)],
    ],
    Discriminator(_item_tag),
]

ItemAdapter: TypeAdapter[Item] = TypeAdapter(Item)

__all__ = [
    "CORE_ITEM_TYPES",
    "CompactionItem",
    "ExtensionItem",
    "FunctionCallItem",
    "FunctionCallOutputItem",
    "Item",
    "ItemAdapter",
    "ItemStatus",
    "MessageItem",
    "MessagePhase",
    "MessageRole",
    "ReasoningItem",
    "ReasoningText",
    "SummaryText",
]
